### ISSUE TITLE
Format Exception

### ISSUE THREAD

**Issue by Dusty-Meg** [LavishSoftware/ISBoxerEVELauncher#27]
Been getting this sporadically when trying to log into some accounts, straight into characters.

System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters. 
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at ISBoxerEVELauncher.EVEAccount.get_Cookies()
   at ISBoxerEVELauncher.EVEAccount.GetAccessToken(Boolean sisi, Token& accessToken)
   at ISBoxerEVELauncher.EVEAccount.GetSSOToken(Boolean sisi, String& ssotoken)
   at ISBoxerEVELauncher.EVEAccount.Launch(String sharedCachePath, Boolean sisi, DirectXVersion dxVersion, Int64 characterID)
   at ISBoxerEVELauncher.Launchers.DirectLauncher.Launch(ILaunchTarget launchTarget)
   at ISBoxerEVELauncher.Windows.LaunchProgressWindow.Timer_Tick(Object sender, EventArgs e)
Account '*** failed to launch: Error. Aborting!

**Comment by Dusty-Meg** [comment]
Upon some debugging the exception is being thrown at
https://github.com/LavishSoftware/ISBoxerEVELauncher/blob/master/EVEAccount.cs#L95
I have added in a quick is base64 string at line 90 to get me past it. This causes the validation code box to open again.
