### ISSUE TITLE
ISBEL Crashes on Launch attempt: NullException

### ISSUE THREAD

**Issue by Ivniinvi** [LavishSoftware/ISBoxerEVELauncher#50]
Whenever I try to launch an account with ISBEL, I get this error:

```
System.ArgumentNullException: Value cannot be null.
Parameter name: stringToEscape
   at System.Uri.EscapeDataString(String stringToEscape)
   at ISBoxerEVELauncher.Games.EVE.EVEAccount.GetAccessToken(Boolean sisi, Token& accessToken)
   at ISBoxerEVELauncher.Games.EVE.EVEAccount.Launch(String sharedCachePath, Boolean sisi, DirectXVersion dxVersion, Int64 characterID)
   at ISBoxerEVELauncher.Launchers.Direct.Launch(ILaunchTarget launchTarget)
   at ISBoxerEVELauncher.Windows.LaunchProgressWindow.Timer_Tick(Object sender, EventArgs e)
Account 'xxxxxxxxxxxxx' failed to launch: Error. Aborting!
```

I've tried reinstalling ISBEL, reinstalling Eve, reinstalling Inner Space, and I still get this error.

**Comment by jsmb768ypl** [comment]
same issue
