### ISSUE TITLE
Cannot launch any account or character

### ISSUE THREAD

**Issue by tillmanj** [LavishSoftware/ISBoxerEVELauncher#53]
Any attempt to launch an account results in:

> System.Net.WebException: The request was aborted: The connection was closed unexpectedly.
>    at System.Net.HttpWebRequest.GetResponse()
>    at ISBoxerEVELauncher.Web.Response..ctor(HttpWebRequest request)
>    at ISBoxerEVELauncher.Web.RequestResponse.GetHttpWebResponse(HttpWebRequest webRequest, Action updateCookies, Response& response)
>    at ISBoxerEVELauncher.Games.EVE.EVEAccount.GetRequestVerificationToken(Uri uri, Boolean sisi, String& verificationToken)
>    at ISBoxerEVELauncher.Games.EVE.EVEAccount.GetAccessToken(Boolean sisi, Token& accessToken)
>    at ISBoxerEVELauncher.Games.EVE.EVEAccount.Launch(String sharedCachePath, Boolean sisi, DirectXVersion dxVersion, Int64 characterID)
>    at ISBoxerEVELauncher.Launchers.Direct.Launch(ILaunchTarget launchTarget)
>    at ISBoxerEVELauncher.Windows.LaunchProgressWindow.Timer_Tick(Object sender, EventArgs e)
> Account 'XXXXXXXXXXXXXX' failed to launch: Error. Aborting!

**Comment by wanjizheng** [comment]
#51
