### ISSUE TITLE
Error when trying to load eve

### ISSUE THREAD

**Issue by dreadddy** [LavishSoftware/ISBoxerEVELauncher#9]
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at ISBoxerEVELauncher.EVEAccount.GetAccessToken(Boolean sisi, HttpWebRequest req, Token& accessToken)
   at ISBoxerEVELauncher.EVEAccount.GetCharacterChallenge(Boolean sisi, Token& accessToken)
   at ISBoxerEVELauncher.EVEAccount.GetAccessToken(Boolean sisi, HttpWebRequest req, Token& accessToken)
   at ISBoxerEVELauncher.EVEAccount.GetAccessToken(Boolean sisi, Token& accessToken)
   at ISBoxerEVELauncher.EVEAccount.GetSSOToken(Boolean sisi, String& ssotoken)
   at ISBoxerEVELauncher.EVEAccount.Launch(String sharedCachePath, Boolean sisi, DirectXVersion dxVersion, Int64 characterID)
   at ISBoxerEVELauncher.Launchers.DirectLauncher.Launch(ILaunchTarget launchTarget)
   at ISBoxerEVELauncher.Windows.LaunchProgressWindow.Timer_Tick(Object sender, EventArgs e)

**Comment by Kane-Larrete** [comment]
This is a symptom but not the problem. It seems to be a problem with 2FA being enabled on accounts. I may have a fix for this and will submit a PR if it works.

**Comment by dreadddy** [comment]
yes it is 2FA i have tested and it works fine without 2FA on

**Comment by LaxLacks** [comment]
ISBEL 1.0.0.16 was released yesterday including a patch to fix 2FA
